# Generated by Django 4.1.3 on 2022-11-30 22:24

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("dashboard", "0001_initial"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="vendedor",
            options={"verbose_name": "Vendedor", "verbose_name_plural": "Vendedores"},
        ),
        migrations.AlterField(
            model_name="vendas",
            name="data",
            field=models.DateTimeField(
                default=datetime.datetime(2022, 11, 30, 19, 24, 35, 579156)
            ),
        ),
    ]
