# Generated by Django 4.1.3 on 2022-11-30 22:27

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("dashboard", "0002_alter_vendedor_options_alter_vendas_data"),
    ]

    operations = [
        migrations.AlterField(
            model_name="vendas",
            name="data",
            field=models.DateTimeField(
                default=datetime.datetime(2022, 11, 30, 19, 27, 49, 715607)
            ),
        ),
    ]
